[env]
RUST_BACKTRACE = 0
CARGO_MAKE_CARGO_BUILD_TEST_FLAGS = "--features tracing-opentelemetry,libquil"  # Disable --all-features to avoid manual tests in CI for now

[tasks.pre-test]
command = "docker"
args = ["compose", "up", "-d"]

[tasks.post-test]
command = "docker"
args = ["compose", "down"]

[tasks.serve-docs]
command = "cargo"
args = ["doc", "--open"]

[tasks.manual]
env = {CARGO_MAKE_CARGO_BUILD_TEST_FLAGS = "--all-features"}
run_task = [{name = "test-flow"}]

[tasks.lint]
dependencies = ["clippy-flow"]

[tasks.examples]
dependencies = ["examples-libquil", "examples-experimental"]

[tasks.examples-libquil]
command = "cargo"
args = ["build", "--examples", "--features", "libquil"]

[tasks.examples-experimental]
command = "cargo"
args = ["build", "--examples", "--features", "experimental"]

[tasks.deny]
install_crate = "cargo-deny"
command = "cargo"
args = ["deny", "--all-features", "check"]

[tasks.pre-ci-flow]
dependencies = ["deny", "lint"]
