[packages.lib]
versioned_files = [
    "crates/lib/Cargo.toml",
    "crates/lib/pyproject.toml",
    "Cargo.lock",
]
changelog = "crates/lib/CHANGELOG.md"
scopes = ["lib", "rust", "python"]

[[workflows]]
name = "release"

[[workflows.steps]]
type = "PrepareRelease"

[[workflows.steps]]
type = "Command"
command = "git commit -m \"chore: prepare new release(s) [skip ci]\""

[[workflows.steps]]
type = "Command"
command = "git push"

[[workflows.steps]]
type = "Release"

[github]
owner = "rigetti"
repo = "qcs-sdk-rust"
