[env]
RUST_BACKTRACE = 0
CARGO_MAKE_CARGO_BUILD_TEST_FLAGS = ""  # Disable --all-features to avoid manual tests in CI for now

[tasks.pre-test]
command = "docker-compose"
args = ["up", "-d"]

[tasks.post-test]
command = "docker-compose"
args = ["down"]

[tasks.serve-docs]
command = "cargo"
args = ["doc", "--open"]

[tasks.manual]
env = {CARGO_MAKE_CARGO_BUILD_TEST_FLAGS = "--all-features"}
run_task = [{name = "test-flow"}]

[tasks.lint]
dependencies = ["clippy-flow"]

[tasks.deny]
install_crate = "cargo-deny"
command = "cargo"
args = ["deny", "--all-features", "check"]

[tasks.pre-ci-flow]
dependencies = ["deny", "lint"]
