[env]
CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = true

[tasks.lint]
workspace = false
dependencies = ["clippy-flow"]

[tasks.deny]
workspace = false
install_crate = "cargo-deny"
command = "cargo"
args = ["deny", "--all-features", "check"]

[tasks.pre-workspace-ci-flow]
dependencies = ["deny", "lint"]
