# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401

import builtins
import collections.abc
import typing
from qcs_sdk import QcsSdkError, RegisterData
from qcs_sdk.qvm.api import AddressRequest
from . import api

@typing.final
class QVMClient:
    @property
    def qvm_url(self) -> builtins.str: ...
    def __new__(cls) -> QVMClient: ...
    @staticmethod
    def new_http(endpoint: builtins.str) -> QVMClient: ...
    @staticmethod
    def new_libquil() -> QVMClient: ...

@typing.final
class QVMOptions:
    r"""
    Options avaialable for running programs on the QVM.
    """
    @property
    def timeout(self) -> typing.Optional[builtins.float]: ...
    @timeout.setter
    def timeout(self, value: typing.Optional[builtins.float]) -> None: ...
    def __new__(cls, timeout_seconds: typing.Optional[builtins.float] = None) -> QVMOptions: ...
    def __repr__(self) -> builtins.str:
        r"""
        Implements `__repr__` for Python in terms of the Rust
        [`Debug`](std::fmt::Debug) implementation.
        """
    @staticmethod
    def default() -> QVMOptions: ...

@typing.final
class QVMResultData:
    r"""
    Encapsulates data returned after running a program on the QVM
    """
    @property
    def memory(self) -> builtins.dict[builtins.str, RegisterData]:
        r"""
        A map of register names (ie. "ro") to a `RegisterData` containing their values.
        """
    def __new__(cls, memory: typing.Mapping[builtins.str, RegisterData]) -> QVMResultData:
        r"""
        Construct a new `QVMResultData` from a memory map.
        """
    @staticmethod
    def from_memory_map(memory: typing.Mapping[builtins.str, RegisterData]) -> QVMResultData:
        r"""
        Build a [`QvmResultData`] from a mapping of register names to a [`RegisterData`]
        """
    def to_raw_readout_data(self) -> RawQVMReadoutData:
        r"""
        Get the raw readout data as a flattened structure.
        """

class QvmError(QcsSdkError):
    r"""
    Errors that can occur when running a Quil program on QVM.
    """
    ...

@typing.final
class RawQVMReadoutData:
    @property
    def memory(self) -> builtins.dict[builtins.str, list]: ...
    def __repr__(self) -> builtins.str:
        r"""
        Implements `__repr__` for Python in terms of the Rust
        [`Debug`](std::fmt::Debug) implementation.
        """

def run(quil: builtins.str, shots: builtins.int, addresses: typing.Mapping[builtins.str, AddressRequest], params: typing.Mapping[builtins.str, typing.Sequence[builtins.float]], client: QVMClient, measurement_noise: typing.Optional[tuple[builtins.float, builtins.float, builtins.float]], gate_noise: typing.Optional[tuple[builtins.float, builtins.float, builtins.float]], rng_seed: typing.Optional[builtins.int], options: typing.Optional[QVMOptions]) -> QVMResultData: ...

def run_async(quil: builtins.str, shots: builtins.int, addresses: typing.Mapping[builtins.str, AddressRequest], params: typing.Mapping[builtins.str, typing.Sequence[builtins.float]], client: QVMClient, measurement_noise: typing.Optional[tuple[builtins.float, builtins.float, builtins.float]], gate_noise: typing.Optional[tuple[builtins.float, builtins.float, builtins.float]], rng_seed: typing.Optional[builtins.int], options: typing.Optional[QVMOptions]) -> collections.abc.Awaitable[QVMResultData]: ...

