[tasks.regenerate]
dependencies = ["generate-client", "format"]

[tasks.generate-client]
command = "docker"
args = [
    "run",
    "--rm",
    "-v",
    "${PWD}:/local",
    "openapitools/openapi-generator-cli",
    "generate",
    "-g",
    "rust",
    "-i",
    "/local/qcs_public.yaml",
    "-o",
    "/local",
]

[tasks.manual]
alias = "empty"