//! Python bindings for the qcs-sdk crate.
//!
//! While this package can be used directly,
//! [PyQuil](https://pypi.org/project/pyquil/) offers more functionality
//! and a higher-level interface for building and executing Quil programs.

use std::sync::OnceLock;

use pyo3::prelude::*;
use rigetti_pyo3::{create_init_submodule, py_sync};

#[cfg(feature = "stubs")]
use pyo3_stub_gen::derive::gen_stub_pyfunction;

use crate::{
    compiler, diagnostics,
    python::{
        executable::{ExeParameter, PyExecutable, PyJobHandle},
        execution_data::{
            PyRegisterMatrix, RegisterMapItemsIter, RegisterMapKeysIter, RegisterMapValuesIter,
        },
    },
    qpu, qvm, ExecutionData, RegisterData, RegisterMap, Service,
};

pub(crate) mod client;
pub(crate) mod errors;
pub(crate) mod executable;
pub(crate) mod execution_data;
pub(crate) mod nonzero;
pub(crate) mod register_data;

pub(crate) use nonzero::NonZeroU16;

static PY_RESET_LOGGING_HANDLE: OnceLock<pyo3_log::ResetHandle> = OnceLock::new();

/// The docstring for the `qcs_sdk` Python package.
///
/// The `__init__.py` files in the package are generated by `pyo3_stub_gen`, which does not
/// write docstrings into them, so this is the only definition of the package docstring:
/// [`init_module`] assigns it to the compiled module, from which the generated
/// `qcs_sdk/__init__.py` re-exports it, and `module_doc!` copies it into the type stubs.
const PACKAGE_DOC: &str =
    "An interface to Rigetti [Quantum Cloud Services](https://docs.rigetti.com/qcs/) (QCS).

These APIs allow users to compile and run Quil programs on Rigetti quantum processors.
Internally, it is powered by the [QCS Rust SDK](https://github.com/rigetti/qcs-sdk-rust).

This package is still in development and breaking changes should be expected between minor versions.
";

create_init_submodule! {
    classes: [
        ExeParameter,
        ExecutionData,
        PyExecutable,
        PyJobHandle,
        RegisterMap,
        RegisterMapItemsIter,
        RegisterMapKeysIter,
        RegisterMapValuesIter,
        Service
    ],

    complex_enums: [ PyRegisterMatrix, RegisterData ],

    errors: [
        errors::QcsSdkError,
        errors::ExecutionError,
        errors::RegisterMatrixConversionError
    ],

    funcs: [ reset_logging, gather_diagnostics ],

    submodules: [
        "client": client::init_submodule,
        "compiler": compiler::python::init_submodule,
        "qpu": qpu::python::init_submodule,
        "qvm": qvm::python::init_submodule,
        "diagnostics": diagnostics::python::init_submodule,
        // Types we borrow from these crates are part of our API surface, but each extension
        // module builds its own copy of their pyclasses: the `Program` we hand back is not the
        // installed `quil` package's `Program`. Registering them here gives our copies a name
        // under `qcs_sdk`, so users have a coherent set of classes to work with.
        "quil": quil_rs::quilpy::init_submodule,
        "common": qcs_api_client_common::init_submodule
    ],
}

#[pymodule]
#[pyo3(name = "_qcs_sdk")]
fn init_module(m: &Bound<'_, PyModule>) -> PyResult<()> {
    match pyo3_log::try_init() {
        Ok(reset_handle) => {
            // Ignore the error if the handle is already set.
            drop(PY_RESET_LOGGING_HANDLE.set(reset_handle));
        }
        Err(e) => eprintln!("Failed to initialize the qcs_sdk logger: {e}"),
    }

    let py = m.py();
    init_submodule("qcs_sdk._qcs_sdk", py, m)?;

    m.add("__version__", env!("CARGO_PKG_VERSION"))?;
    m.setattr("__doc__", PACKAGE_DOC)?;

    // Registered under the public `qcs_sdk` name rather than `qcs_sdk._qcs_sdk`: the
    // corresponding Python source is generated into `python/qcs_sdk/_tracing_subscriber` by
    // `pyo3_tracing_subscriber_build`, so `qcs_sdk._tracing_subscriber` is its import path.
    pyo3_tracing_subscriber::add_submodule("qcs_sdk", "_tracing_subscriber", py, m)?;

    Ok(())
}

#[cfg(feature = "stubs")]
mod stubs {
    use pyo3_stub_gen::{
        define_stub_info_gatherer,
        generate::{ClassDef as Module_ClassDef, Module},
        module_doc, reexport_module_members, ImportRef, ModuleRef, Result, StubInfo, TypeInfo,
    };
    use std::path::Path;

    #[derive(pyo3::IntoPyObject)]
    struct Final<T>(T);

    impl<T> pyo3_stub_gen::PyStubType for Final<T>
    where
        T: pyo3_stub_gen::PyStubType,
    {
        fn type_output() -> pyo3_stub_gen::TypeInfo {
            let mut inner = T::type_output();
            inner.import.insert("typing".into());
            inner.name = format!("typing.Final[{}]", inner.name);
            inner
        }
    }

    pyo3_stub_gen::module_variable!("qcs_sdk._qcs_sdk", "__version__", Final<&str>);

    pyo3_stub_gen::module_variable!(
        "qcs_sdk._qcs_sdk.compiler.quilc",
        "DEFAULT_COMPILER_TIMEOUT",
        Final<f64>
    );

    pyo3_stub_gen::module_doc!("qcs_sdk._qcs_sdk", "{}", super::PACKAGE_DOC);

    // `client::init_submodule` adds these `qcs_api_client_common` types to `qcs_sdk.client`,
    // but they carry that crate's own module annotation, so nothing declares them as members of
    // ours: they would be missing from the generated `__init__.py` and undefined in the stubs.
    // Aliasing them here registers them as members of the module that actually exposes them.
    // (`scripts/lint-bindings.py` keeps a matching list, for the same reason.)
    mod client_reexports {
        use pyo3_stub_gen::type_alias;
        use qcs_api_client_common::configuration::{
            secrets::SecretRefreshToken as CommonSecretRefreshToken,
            settings::AuthServer as CommonAuthServer,
            tokens::{
                ClientCredentials as CommonClientCredentials,
                ExternallyManaged as CommonExternallyManaged, OAuthSession as CommonOAuthSession,
                RefreshToken as CommonRefreshToken,
            },
        };

        type_alias!("qcs_sdk._qcs_sdk.client", AuthServer = CommonAuthServer);
        type_alias!("qcs_sdk._qcs_sdk.client", ClientCredentials = CommonClientCredentials);
        type_alias!("qcs_sdk._qcs_sdk.client", ExternallyManaged = CommonExternallyManaged);
        type_alias!("qcs_sdk._qcs_sdk.client", OAuthSession = CommonOAuthSession);
        type_alias!("qcs_sdk._qcs_sdk.client", RefreshToken = CommonRefreshToken);
        type_alias!("qcs_sdk._qcs_sdk.client", SecretRefreshToken = CommonSecretRefreshToken);
    }

    // During stub generation, these `qcs_sdk._qcs_sdk` modules and their contents are
    // re-exported into the public `qcs_sdk` namespace, and the corresponding `__init__.py`
    // files are generated. Every module in the tree built by `create_init_submodule!` needs an
    // entry here: the compiled modules register themselves under `qcs_sdk._qcs_sdk.*`, so the
    // public `qcs_sdk.*` import paths exist only by way of these generated packages.
    reexport_module_members!("qcs_sdk" from "qcs_sdk._qcs_sdk"; *, "__doc__", "__version__");
    reexport_module_members!("qcs_sdk.client" from "qcs_sdk._qcs_sdk.client");
    reexport_module_members!("qcs_sdk.compiler" from "qcs_sdk._qcs_sdk.compiler");
    // `DEFAULT_COMPILER_TIMEOUT` is a `consts:` entry in `create_init_submodule!`, which the
    // wildcard doesn't see; `module_variable!` below gives it a type in the stubs.
    reexport_module_members!(
        "qcs_sdk.compiler.quilc" from "qcs_sdk._qcs_sdk.compiler.quilc";
        *,
        "DEFAULT_COMPILER_TIMEOUT"
    );
    reexport_module_members!("qcs_sdk.diagnostics" from "qcs_sdk._qcs_sdk.diagnostics");
    reexport_module_members!("qcs_sdk.qpu" from "qcs_sdk._qcs_sdk.qpu");
    reexport_module_members!("qcs_sdk.qpu.api" from "qcs_sdk._qcs_sdk.qpu.api");
    reexport_module_members!("qcs_sdk.qpu.experimental" from "qcs_sdk._qcs_sdk.qpu.experimental");
    reexport_module_members!(
        "qcs_sdk.qpu.experimental.random" from "qcs_sdk._qcs_sdk.qpu.experimental.random"
    );
    reexport_module_members!("qcs_sdk.qpu.isa" from "qcs_sdk._qcs_sdk.qpu.isa");
    reexport_module_members!("qcs_sdk.qpu.translation" from "qcs_sdk._qcs_sdk.qpu.translation");
    reexport_module_members!("qcs_sdk.qvm" from "qcs_sdk._qcs_sdk.qvm");
    reexport_module_members!("qcs_sdk.qvm.api" from "qcs_sdk._qcs_sdk.qvm.api");

    // `QCSClient` has always been available at the top level, in addition to `qcs_sdk.client`.
    reexport_module_members!("qcs_sdk" from "qcs_sdk._qcs_sdk.client"; "QCSClient");

    // `_tracing_subscriber` is generated by `pyo3_tracing_subscriber_build` rather than by
    // `pyo3_stub_gen`, so it has to be named explicitly. Sourcing it from the package itself
    // generates `from qcs_sdk import _tracing_subscriber`, which resolves the generated
    // subpackage through the partially-initialized package in `sys.modules`.
    reexport_module_members!("qcs_sdk" from "qcs_sdk"; "_tracing_subscriber");

    // `StubInfo` resolves every wildcard re-export it can see, including those declared by our
    // dependencies, and fails if a source module has no registered members. `quil-rs` declares
    // `quil.validation` from `quil._quil.validation`, whose only content is a submodule, so it
    // registers that module imperatively in its own `stub_gen` binary — meaning it does not
    // exist here and resolution fails. Declaring the module (with no docstring) registers it,
    // after which `stub_info` drops it along with the rest of the foreign modules.
    module_doc!("quil._quil.validation", "");

    define_stub_info_gatherer!(internal_stub_info);

    /// Ensures modules exist in the stubs, even if they don't have any members.
    fn ensure_submod(stubs: &mut StubInfo, module: &str) {
        stubs.modules.entry(module.to_string()).or_insert(Module {
            name: module.to_string(),
            ..Default::default()
        });

        if let Some((parent, child)) = module.rsplit_once('.') {
            stubs
                .modules
                .entry(parent.to_string())
                .or_insert(Module {
                    name: parent.to_string(),
                    ..Default::default()
                })
                .submodules
                .insert(child.to_string());

            ensure_submod(stubs, parent);
        }
    }


    /// Foreign module trees that `init_module` re-registers under our own package, paired with
    /// the module path they are registered as. See [`rehome_module_tree`].
    ///
    /// `quil._quil` is deliberately absent: `quil-rs` post-processes its own generated stubs in
    /// its `stub_gen` binary — resolving `$SELF` and parameterizing generic `self` types — and
    /// that pass is not reachable from here, so a relocated `quil` tree would carry unresolved
    /// placeholders. Its one reference site is handled by a `gen_stub` type override instead.
    const FOREIGN_MODULE_ROOTS: [(&str, &str); 1] = [(
        "qcs_api_client_common._qcs_api_client_common",
        "qcs_sdk._qcs_sdk.common",
    )];

    /// Move every module under `foreign_root` to the same position under `local_root`, and
    /// retarget every reference to those modules across the whole stub tree.
    ///
    /// Each extension module builds its own copy of a linked crate's `#[pyclass]`es, so the
    /// `Program` we return is not the installed `quil` package's `Program` — it is ours, and
    /// `init_module` gives it a name under `qcs_sdk`. Relocating the declarations makes the
    /// stubs say the same thing. It also makes the modules internal, so `pyo3_stub_gen` writes
    /// `from qcs_sdk._qcs_sdk.quil import program` instead of the `import quil._quil.program`
    /// form it uses for foreign modules — which binds only `quil`, leaving the `program.Program`
    /// references it emits undefined.
    fn rehome_module_tree(stubs: &mut StubInfo, foreign_root: &str, local_root: &str) {
        let rehomed = |name: &str| -> Option<String> {
            if name == foreign_root {
                Some(local_root.to_string())
            } else {
                name.strip_prefix(&format!("{foreign_root}."))
                    .map(|rest| format!("{local_root}.{rest}"))
            }
        };

        let moved: Vec<(String, String)> = stubs
            .modules
            .keys()
            .filter_map(|name| rehomed(name).map(|local| (name.clone(), local)))
            .collect();

        for (foreign, local) in moved {
            let Some(mut module) = stubs.modules.remove(&foreign) else {
                continue;
            };

            // `name` is the module's own path; `default_module_name` is the package root that
            // `ModuleRef::Default` resolves to, which is ours now.
            local.clone_into(&mut module.name);
            module.default_module_name = "qcs_sdk._qcs_sdk".to_string();
            for class in module.class.values_mut() {
                rehome_class(class, &local);
            }
            for enum_ in module.enum_.values_mut() {
                enum_.module = Some(leak(local.clone()));
            }

            stubs.modules.insert(local.clone(), module);
            ensure_submod(stubs, &local);
        }

        // A type is named by its module's last component — `configuration.OAuthSession` — so
        // where re-homing changes that component, the references have to be renamed too:
        // `qcs_api_client_common._qcs_api_client_common` becomes `common`.
        let renamed_leaf = leaf(foreign_root) != leaf(local_root);

        // References live in every module, not just the relocated ones: `Qcs` sits in
        // `qcs_sdk._qcs_sdk.client` and returns a `qcs_api_client_common` type.
        for module in stubs.modules.values_mut() {
            retarget_module_refs(module, &rehomed, renamed_leaf.then(|| (leaf(foreign_root), leaf(local_root))));
        }
    }

    /// Point a class, its nested classes, and its members at `module`.
    fn rehome_class(class: &mut Module_ClassDef, module: &str) {
        class.module = Some(leak(module.to_string()));
        for nested in &mut class.classes {
            rehome_class(nested, module);
        }
    }

    /// Rewrite every module path a type reference names, using `rehomed` to map old to new.
    fn retarget_module_refs(
        module: &mut Module,
        rehomed: &impl Fn(&str) -> Option<String>,
        renamed_leaf: Option<(&str, &str)>,
    ) {
        let mut retarget =
            |type_info: &mut TypeInfo| retarget_type_info(type_info, rehomed, renamed_leaf);

        for class in module.class.values_mut() {
            visit_class_types(class, &mut retarget);
        }
        for enum_ in module.enum_.values_mut() {
            for method in &mut enum_.methods {
                visit_method_types(method, &mut retarget);
            }
            for member in enum_
                .attrs
                .iter_mut()
                .chain(&mut enum_.getters)
                .chain(&mut enum_.setters)
            {
                retarget(&mut member.r#type);
            }
        }
        for function in module.function.values_mut().flatten() {
            visit_parameter_types(&mut function.parameters, &mut retarget);
            retarget(&mut function.r#return);
        }
        for variable in module.variables.values_mut() {
            retarget(&mut variable.type_);
        }
        for alias in module.type_aliases.values_mut() {
            retarget(&mut alias.type_);
        }
    }

    fn visit_class_types(class: &mut Module_ClassDef, retarget: &mut impl FnMut(&mut TypeInfo)) {
        for base in &mut class.bases {
            retarget(base);
        }
        for member in &mut class.attrs {
            retarget(&mut member.r#type);
        }
        for (getter, setter) in class.getter_setters.values_mut() {
            for member in getter.iter_mut().chain(setter.iter_mut()) {
                retarget(&mut member.r#type);
            }
        }
        for method in class.methods.values_mut().flatten() {
            visit_method_types(method, retarget);
        }
        for nested in &mut class.classes {
            visit_class_types(nested, retarget);
        }
    }

    fn visit_method_types(
        method: &mut pyo3_stub_gen::generate::MethodDef,
        retarget: &mut impl FnMut(&mut TypeInfo),
    ) {
        visit_parameter_types(&mut method.parameters, retarget);
        retarget(&mut method.r#return);
    }

    fn visit_parameter_types(
        parameters: &mut pyo3_stub_gen::generate::Parameters,
        retarget: &mut impl FnMut(&mut TypeInfo),
    ) {
        for parameter in parameters
            .positional_only
            .iter_mut()
            .chain(&mut parameters.positional_or_keyword)
            .chain(&mut parameters.keyword_only)
            .chain(&mut parameters.varargs)
            .chain(&mut parameters.varkw)
        {
            retarget(&mut parameter.type_info);
        }
    }

    /// Rewrite the module paths in a single type reference: where the type is declared, what has
    /// to be imported to name it, and the per-identifier map the generator uses to qualify it.
    fn retarget_type_info(
        type_info: &mut TypeInfo,
        rehomed: &impl Fn(&str) -> Option<String>,
        renamed_leaf: Option<(&str, &str)>,
    ) {
        let retarget_module_ref = |module: &mut ModuleRef| {
            if let ModuleRef::Named(name) = module {
                if let Some(local) = rehomed(name) {
                    *name = local;
                }
            }
        };

        if let Some(source_module) = type_info.source_module.as_mut() {
            retarget_module_ref(source_module);
        }
        type_info.import = type_info
            .import
            .drain()
            .map(|mut import| {
                if let ImportRef::Module(module) = &mut import {
                    retarget_module_ref(module);
                }
                import
            })
            .collect();
        for type_ref in type_info.type_refs.values_mut() {
            retarget_module_ref(&mut type_ref.module);
        }
        if let Some((foreign_leaf, local_leaf)) = renamed_leaf {
            type_info.name = type_info
                .name
                .replace(&format!("{foreign_leaf}."), &format!("{local_leaf}."));
        }
    }

    /// The last component of a dotted module path, which is how types from that module are named.
    fn leaf(module: &str) -> &str {
        module.rsplit('.').next().unwrap_or(module)
    }

    /// `ClassDef::module` and `EnumDef::module` are `&'static str`, so a computed path has to
    /// outlive the generation run. It does — this is a one-shot binary.
    fn leak(value: String) -> &'static str {
        Box::leak(value.into_boxed_str())
    }

    /// Gather stub information to generate stub files.
    pub fn stub_info() -> Result<StubInfo> {
        let manifest_dir: &Path = env!("CARGO_MANIFEST_DIR").as_ref();
        let mut stubs = StubInfo::from_pyproject_toml(manifest_dir.join("pyproject.toml"))?;

        // `pyo3_stub_gen` gathers declarations from every linked crate, so dependencies that
        // define their own Python packages — `quil-rs`, `qcs-api-client-common` — contribute
        // their modules here too. `init_module` registers those crates' classes under
        // `qcs_sdk._qcs_sdk.quil` and `qcs_sdk._qcs_sdk.common`, because the class objects our
        // extension module creates are its own, distinct from the ones the installed `quil` and
        // `qcs_api_client_common` packages create. Move their declarations to match, so the
        // stubs describe the classes we actually hand out rather than the other packages'.
        for (foreign_root, local_root) in FOREIGN_MODULE_ROOTS {
            rehome_module_tree(&mut stubs, foreign_root, local_root);
        }

        // Anything still outside our module path is a foreign module we do not re-export.
        // Generation rejects any non-empty module outside this package's module path, and
        // writing files for them would shadow the real, installed packages, so drop them.
        stubs
            .modules
            .retain(|name, _| name == "qcs_sdk" || name.starts_with("qcs_sdk."));

        // Add otherwise empty modules, as they aren't found automatically.
        let module_leaves = [
            "qcs_sdk._qcs_sdk.compiler.quilc",
            "qcs_sdk._qcs_sdk.qpu.experimental.random",
            "qcs_sdk._qcs_sdk.qvm",
        ];

        for mod_name in module_leaves {
            ensure_submod(&mut stubs, mod_name);
        }

        Ok(stubs)
    }
}

#[cfg(feature = "stubs")]
pub use stubs::stub_info;

#[cfg_attr(feature = "stubs", gen_stub_pyfunction(module = "qcs_sdk._qcs_sdk"))]
#[pyfunction]
/// Reset all caches for logging configuration within this library,
/// allowing the most recent Python-side changes to be applied.
///
/// See <https://docs.rs/pyo3-log/latest/pyo3_log/> for more information.
fn reset_logging() {
    if let Some(handle) = PY_RESET_LOGGING_HANDLE.get() {
        handle.reset();
    }
}

#[cfg_attr(feature = "stubs", gen_stub_pyfunction(module = "qcs_sdk._qcs_sdk"))]
#[pyfunction]
#[pyo3(name = "_gather_diagnostics")]
fn gather_diagnostics(py: Python<'_>) -> PyResult<String> {
    py_sync!(py, async { Ok(diagnostics::get_report().await) })
}
