# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405
r"""
A suite of common functionalities for QCS client applications.

This package offers reusable middleware implementations
that can be integrated into various client libraries.
This allows for consistent behavior across different projects
and facilitates easier maintenance and scalability of client-side logic.

⚠️ This package is still in early development
and breaking changes should be expected between minor versions.
"""

import builtins
from . import configuration

__all__ = [
    "QcsApiClientError",
    "configuration",
]

class QcsApiClientError(builtins.Exception):
    r"""
    Base exception type for errors raised by this package.
    """

    ...
