[env]
RUST_BACKTRACE = 0

[tasks.pre-test-docker-up]
command = "docker-compose"
args = ["up", "-d"]

[tasks.poetry-install]
command = "poetry"
args = ["install"]

[tasks.install-lib]
command = "poetry"
args = ["run", "maturin", "develop"]

[tasks.post-test]
command = "docker-compose"
args = ["down"]

[tasks.test]
command = "poetry"
args = ["run", "pytest", "tests"]

[tasks.test-session]
command = "poetry"
args = ["run", "pytest", "tests", "--with-qcs-session"]

[tasks.test-execution]
command = "poetry"
args = ["run", "pytest", "tests", "--with-qcs-session", "--with-qcs-execution"]

[tasks.pytest-flow]
dependencies = [
    "pre-test-docker-up",
    "poetry-install",
    "install-lib",
    "test",
    "post-test",
]

[tasks.stubtest]
command = "poetry"
args = ["run", "stubtest", "--allowlist", ".stubtest-allowlist", "qcs_sdk"]

[tasks.stubtest-flow]
dependencies = [
    "poetry-install",
    "install-lib",
    "stubtest",
]

[tasks.dev-flow]
dependencies = ["dev-test-flow", "pytest-flow", "stubtest"]

[tasks.default]
alias = "dev-flow"

[tasks.ci-flow]
dependencies = ["pytest-flow", "stubtest"]
