# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401

import builtins
import typing
from qcs_sdk import QcsSdkError

class CompilationResult:
    @property
    def native_quil_metadata(self) -> typing.Optional[NativeQuilMetadata]: ...
    @property
    def program(self) -> builtins.str: ...

class CompilerOpts:
    r"""
    A set of options that determine the behavior of compiling programs with quilc
    """
    def __new__(cls, timeout:typing.Optional[builtins.float]=30.0, protoquil:typing.Optional[builtins.bool]=None) -> CompilerOpts:
        r"""
        Creates a new instance of [`CompilerOpts`] with zero values for each option.
        
        Consider using [`CompilerOpts::default()`] to create an instance with recommended defaults.
        """
    @staticmethod
    def default() -> CompilerOpts: ...

class ConjugateByCliffordRequest:
    r"""
    Request to conjugate a Pauli Term by a Clifford element.
    """
    @property
    def clifford(self) -> builtins.str:
        r"""
        Clifford element.
        """
    @property
    def pauli(self) -> PauliTerm:
        r"""
        Pauli Term to conjugate.
        """
    def __new__(cls, pauli:PauliTerm, clifford:builtins.str) -> ConjugateByCliffordRequest: ...

class ConjugatePauliByCliffordRequest:
    r"""
    The "outer" request shape for a `conjugate_pauli_by_clifford` request.
    """
    @property
    def args(self) -> builtins.list[ConjugateByCliffordRequest]: ...

class ConjugatePauliByCliffordResponse:
    r"""
    Conjugate Pauli by Clifford response.
    """
    @property
    def pauli(self) -> builtins.str:
        r"""
        Description of the encoded Pauli.
        """
    @property
    def phase(self) -> builtins.int:
        r"""
        Encoded global phase factor on the emitted Pauli.
        """

class GenerateRandomizedBenchmarkingSequenceResponse:
    r"""
    Randomly generated benchmarking sequence response.
    """
    @property
    def sequence(self) -> builtins.list[builtins.list[builtins.int]]:
        r"""
        List of Cliffords, each expressed as a list of generator indices.
        """

class NativeQuilMetadata:
    r"""
    Metadata about a program compiled to native quil.
    """
    def __eq__(self, other:builtins.object) -> builtins.bool: ...
    def __new__(cls, final_rewiring:typing.Optional[typing.Sequence[builtins.int]], gate_depth:typing.Optional[builtins.int], gate_volume:typing.Optional[builtins.int], multiqubit_gate_depth:typing.Optional[builtins.int], program_duration:typing.Optional[builtins.float], program_fidelity:typing.Optional[builtins.float], topological_swaps:typing.Optional[builtins.int], qpu_runtime_estimation:typing.Optional[builtins.float]) -> NativeQuilMetadata: ...

class PauliTerm:
    r"""
    Pauli Term
    """
    @property
    def indices(self) -> builtins.list[builtins.int]:
        r"""
        Qubit indices onto which the factors of the Pauli term are applied.
        """
    @property
    def symbols(self) -> builtins.list[builtins.str]:
        r"""
        Ordered factors of the Pauli term.
        """
    def __new__(cls, indices:typing.Sequence[builtins.int], symbols:typing.Sequence[builtins.str]) -> PauliTerm: ...

class PyInstructionSetArchitecture:
    ...

class QuilcClient:
    def __new__(cls) -> QuilcClient: ...
    @staticmethod
    def new_libquil() -> QuilcClient: ...
    @staticmethod
    def new_rpcq(endpoint:builtins.str) -> QuilcClient: ...

class QuilcError(QcsSdkError):
    r"""
    Errors encountered compiling a Quil program.
    """
    ...

class RandomizedBenchmarkingRequest:
    r"""
    Request to generate a randomized benchmarking sequence.
    """
    @property
    def depth(self) -> builtins.int:
        r"""
        Depth of the benchmarking sequence.
        """
    @property
    def gateset(self) -> builtins.list[builtins.str]:
        r"""
        List of Quil programs, each describing a Clifford.
        """
    @property
    def interleaver(self) -> typing.Optional[builtins.str]:
        r"""
        Fixed Clifford, specified as a Quil string, to interleave through an RB sequence.
        """
    @property
    def qubits(self) -> builtins.int:
        r"""
        Number of qubits involved in the benchmarking sequence.
        """
    @property
    def seed(self) -> typing.Optional[builtins.int]:
        r"""
        PRNG seed. Set this to guarantee repeatable results.
        """
    def __new__(cls, depth:builtins.int, qubits:builtins.int, gateset:typing.Sequence[builtins.str], seed:typing.Optional[builtins.int], interleaver:typing.Optional[builtins.str]) -> RandomizedBenchmarkingRequest: ...

class TargetDevice:
    r"""
    Description of a device to compile for.
    """
    @staticmethod
    def from_isa(isa:PyInstructionSetArchitecture) -> TargetDevice: ...
    @staticmethod
    def from_json(value:builtins.str) -> TargetDevice: ...

def compile_program(quil:builtins.str, target:TargetDevice, client:QuilcClient, options:typing.Optional[CompilerOpts]=None) -> CompilationResult: ...

def compile_program_async(quil:builtins.str, target:TargetDevice, client:QuilcClient, options:typing.Optional[CompilerOpts]=None) -> typing.Any: ...

def conjugate_pauli_by_clifford(request:ConjugateByCliffordRequest, client:QuilcClient) -> ConjugatePauliByCliffordResponse: ...

def conjugate_pauli_by_clifford_async(request:ConjugateByCliffordRequest, client:QuilcClient) -> typing.Any: ...

def generate_randomized_benchmarking_sequence(request:RandomizedBenchmarkingRequest, client:QuilcClient) -> GenerateRandomizedBenchmarkingSequenceResponse: ...

def generate_randomized_benchmarking_sequence_async(request:RandomizedBenchmarkingRequest, client:QuilcClient) -> typing.Any: ...

def get_version_info(client:QuilcClient) -> builtins.str: ...

def get_version_info_async(client:QuilcClient) -> typing.Any: ...

