#!/usr/bin/env bash

if [[ $# -ne 0 ]]; then
    echo "Usage: $0"
    echo "Installs quilc, the Quil compiler."
    exit 0
fi

if hash quilc; then
    echo "quilc is already installed. Skipping installation."
    exit 0
fi

if [[ $UID -ne 0 ]]; then
    echo "Rerunning with 'sudo'..."
    exec sudo "$0"
fi

apt update
apt install -y libffi\* libblas\* liblapack\* curl
curl -O https://mirrors.edge.kernel.org/ubuntu/pool/main/libf/libffi/libffi7_3.3-4_amd64.deb
apt install -y ./libffi7_3.3-4_amd64.deb
rm libffi7_3.3-4_amd64.deb
apt install -y libffi-dev

curl https://raw.githubusercontent.com/rigetti/libquil/main/install.sh | bash -s 0.3.0
