[book]
authors = ["Dylan Anthony"]
language = "en"
multilingual = false
src = "src"
title = "QCS SDK"

[output.html]
additional-js =["mermaid.min.js", "mermaid-init.js"]

[output.linkcheck]
[preprocessor]
[preprocessor.mermaid]
command = "mdbook-mermaid"
