name: Prepare Release

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      type:
        description: Bump versions and trigger a new release.
        required: true
        default: release
        options:
          - release
          - prerelease

jobs:
  prepare-release:
    runs-on: ubuntu-latest
    env:
      REMOTE_REPO: https://${{ github.actor }}:${{ github.token }}@github.com/${{ github.repository }}.git
      GITHUB_TOKEN: ${{ github.token }}
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Install Knope
      uses: knope-dev/action@v1
      with:
        version: 0.6.1 # Test before updating, breaking changes likely: https://github.com/knope-dev/action#install-latest-version
    - run: |
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config user.name "github-actions[bot]"
        git remote set-url origin "${REMOTE_REPO}"
    - name: Prepare Prerelease
      run: knope prerelease
      if: github.event_name == 'push'
    - name: Prepare Release
      run: knope ${{ inputs.type }}
      if: github.event_name == 'workflow_dispatch'
