name: Prepare Release

# TODO: This should be changed to workflow-dispatch before being merged to main
on:
  push:
    branches:
      - main
      - 135-python-bindings-distribution

jobs:
  prepare-release:
    runs-on: ubuntu-latest
    env:
      REMOTE_REPO: "https://${GITHUB_ACTOR}:${secrets.GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git"
    steps:
    - uses: actions/checkout@v2
    - run: |
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config user.name "github-actions[bot]"
        git remote set-url origin "${REMOTE_REPO}"
        knope prerelease
