name: Release Rust

on:
  release:
    types: [published]
  workflow_dispatch:
    description: "Manually publish release"

jobs:
  is-lib-release:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'workflow_dispatch' || startsWith(github.event.release.tag_name, 'lib/v') }}
    steps:
      - run: echo "Release tag starts with lib/v, proceeding with release"

  release:
    runs-on: ubuntu-latest
    needs: is-lib-release
    env:
      CXXFLAGS: "-std=c++11"
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.PAT }}
      - name: Install protoc
        uses: arduino/setup-protoc@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          version: '3.20.1'
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - run: cargo publish --manifest-path=crates/lib/Cargo.toml --token ${{ secrets.CRATES_IO_TOKEN }}
