name: Run Python Wheel Checks
on:
  pull_request:

jobs:
  macos:
    runs-on: macos-latest
    env:
      CXXFLAGS: "-std=c++11 -stdlib=libc++"
    strategy:
      matrix:
        package-name: [qcs-sdk-python, qcs-sdk-python-grpc-web]
        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12"]
    steps:
    - uses: actions/checkout@v4
    - name: Install protoc
      uses: arduino/setup-protoc@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        version: '3.20.1'
    - uses: ./.github/action-common-python-release-test
      with:
        package-name: ${{ matrix.package-name }}
        python-version: ${{ matrix.python-version }}
        maturin-target: universal2-apple-darwin

  linux-x86_64:
    runs-on: ubuntu-latest
    env:
      CXXFLAGS: "-std=c++11"
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12"]
    steps:
    - uses: actions/checkout@v4
    - name: Install protoc
      uses: arduino/setup-protoc@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        version: '3.20.1'
    - uses: ./.github/action-common-python-release-test
      with:
        package-name: qcs-sdk-python
        python-version: ${{ matrix.python-version }}
        maturin-target: x86_64

  linux-aarch64:
    runs-on: ubuntu-24.04-arm
    env:
      CXXFLAGS: "-std=c++11"
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12"]
    steps:
    - uses: actions/checkout@v4
    - name: Install protoc
      uses: arduino/setup-protoc@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        version: '3.20.1'
    - uses: ./.github/action-common-python-release-test
      with:
        package-name: qcs-sdk-python
        python-version: ${{ matrix.python-version }}
        maturin-target: aarch64

  linux-grpc-web:
    runs-on: ubuntu-latest
    env:
      CXXFLAGS: "-std=c++11"
    strategy:
      matrix:
        target: [x86_64, ppc64le]
        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12"]
    steps:
    - uses: actions/checkout@v4
    - name: Install protoc
      uses: arduino/setup-protoc@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        version: '3.20.1'
    - uses: ./.github/action-common-python-release-test
      with:
        package-name: qcs-sdk-python-grpc-web
        python-version: ${{ matrix.python-version }}
        maturin-target: ${{ matrix.target }}

  windows:
    runs-on: windows-latest
    strategy:
      matrix:
        package-name: [qcs-sdk-python, qcs-sdk-python-grpc-web]
        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12"]
    steps:
    - name: Enable long path support
      run: |
        reg add "HKLM\SYSTEM\CurrentControlSet\Control\FileSystem" /v LongPathsEnabled /t REG_DWORD /d 1 /f
        git config --system core.longpaths true
    - uses: actions/checkout@v4
    - name: Install protoc
      uses: arduino/setup-protoc@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        version: '3.20.1'
    - uses: ./.github/action-common-python-release-test
      with:
        package-name: ${{ matrix.package-name }}
        python-version: ${{ matrix.python-version }}
        python-architecture: x64
        rust-target: x86_64-pc-windows-msvc

