# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401

import builtins
import collections.abc
import datetime
import typing
from qcs_sdk import QcsSdkError
from qcs_sdk.client import QCSClient
from qcs_sdk.qpu import ConnectionStrategy, MemoryValues

@typing.final
class APIExecutionOptions:
    r"""
    Options available when executing a job on a QPU, particular to the execution service's API.
    This is a conventent alias for [`InnerApiExecutionOptions`] which provides a builder.
    
    Use [`Default`] to get a reasonable set of defaults, or start with [`ApiExecutionOptionsBuilder`]
    to build a custom set of options.
    """
    @property
    def bypass_settings_protection(self) -> builtins.bool:
        r"""
        Get the configured `bypass_settings_protection` value.
        """
    @property
    def timeout(self) -> typing.Optional[QpuApiDuration]:
        r"""
        Get the configured `timeout` value.
        
        Note, this is the timeout while running a job; the job will be evicted from
        the hardware once this time has elapsed.
        
        If unset, the job's estimated duration will be used;
        if the job does not have an estimated duration, the default
        timeout is selected by the service.
        
        The service may also enforce a maximum value for this field.
        """
    def __repr__(self) -> builtins.str:
        r"""
        Implements `__repr__` for Python in terms of the Rust
        [`Debug`](std::fmt::Debug) implementation.
        """
    @staticmethod
    def builder() -> APIExecutionOptionsBuilder:
        r"""
        Get an [`ExecutionOptionsBuilder`] that can be used to build a custom [`ExecutionOptions`].
        """
    @staticmethod
    def default() -> APIExecutionOptions: ...

@typing.final
class APIExecutionOptionsBuilder:
    r"""
    Builder for [`ApiExecutionOptions`](struct.ApiExecutionOptions.html).
    """
    @bypass_settings_protection.setter
    def bypass_settings_protection(self, value: builtins.bool) -> None: ...
    @timeout.setter
    def timeout(self, value: typing.Optional[QpuApiDuration]) -> None: ...
    def __new__(cls) -> APIExecutionOptionsBuilder: ...
    def build(self) -> APIExecutionOptions: ...
    @staticmethod
    def default() -> APIExecutionOptionsBuilder: ...

class BuildOptionsError(QpuApiError):
    r"""
    Errors building execution options.
    """
    ...

@typing.final
class ExecutionOptions:
    r"""
    Options available when executing a job on a QPU.
    
    Use [`Default`] to get a reasonable set of defaults, or start with [`ExecutionOptionsBuilder`]
    to build a custom set of options.
    """
    @property
    def api_options(self) -> typing.Optional[APIExecutionOptions]: ...
    @property
    def connection_strategy(self) -> ConnectionStrategy:
        r"""
        The [`ConnectionStrategy`] to use to establish a connection to the QPU.
        """
    @property
    def timeout_seconds(self) -> typing.Optional[builtins.float]: ...
    def __eq__(self, other: builtins.object) -> builtins.bool: ...
    def __getnewargs__(self) -> tuple[ConnectionStrategy, typing.Optional[datetime.timedelta], typing.Optional[APIExecutionOptions]]: ...
    def __new__(cls, connection_strategy: ConnectionStrategy = ..., timeout: typing.Optional[datetime.timedelta] = ..., api_options: typing.Optional[APIExecutionOptions] = None) -> ExecutionOptions: ...
    def __repr__(self) -> builtins.str:
        r"""
        Implements `__repr__` for Python in terms of the Rust
        [`Debug`](std::fmt::Debug) implementation.
        """
    @staticmethod
    def builder() -> ExecutionOptionsBuilder: ...
    @staticmethod
    def default() -> ExecutionOptions: ...

@typing.final
class ExecutionOptionsBuilder:
    ...

@typing.final
class ExecutionOptionsBuilder:
    r"""
    Builder for [`ExecutionOptions`](struct.ExecutionOptions.html).
    """
    @api_options.setter
    def api_options(self, value: typing.Optional[APIExecutionOptions]) -> None: ...
    @connection_strategy.setter
    def connection_strategy(self, value: ConnectionStrategy) -> None: ...
    @timeout_seconds.setter
    def timeout_seconds(self, value: typing.Optional[builtins.float]) -> None: ...
    def __new__(cls) -> ExecutionOptionsBuilder: ...
    def build(self) -> ExecutionOptions: ...
    @staticmethod
    def default() -> ExecutionOptionsBuilder: ...

@typing.final
class ExecutionResult:
    r"""
    The execution readout data from a particular memory location.
    """
    @property
    def data(self) -> Register:
        r"""
        Register data for this result.
        """
    @property
    def dtype(self) -> builtins.str:
        r"""
        Name of the data type.
        """
    @property
    def shape(self) -> builtins.list[builtins.int]:
        r"""
        Describes result shape dimensions.
        """
    @staticmethod
    def from_register(register: Register) -> ExecutionResult: ...

@typing.final
class ExecutionResults:
    @property
    def buffers(self) -> builtins.dict[builtins.str, ExecutionResult]:
        r"""
        Result data buffers keyed by readout alias name.
        """
    @property
    def execution_duration_microseconds(self) -> typing.Optional[builtins.int]:
        r"""
        QPU execution duration.
        """
    @property
    def memory(self) -> builtins.dict[builtins.str, MemoryValues]: ...
    def __new__(cls, buffers: typing.Mapping[builtins.str, ExecutionResult], memory: typing.Mapping[builtins.str, MemoryValues], execution_duration_microseconds: typing.Optional[builtins.int]) -> ExecutionResults: ...

@typing.final
class QpuApiDuration:
    @property
    def nanos(self) -> builtins.int: ...
    @property
    def seconds(self) -> builtins.int: ...
    def __new__(cls, seconds: builtins.int, nanos: builtins.int) -> QpuApiDuration: ...

class QpuApiError(QcsSdkError):
    r"""
    Errors that can occur while attempting to establish a connection to the QPU.
    """
    ...

class Register:
    r"""
    Variants of data vectors within a single `ExecutionResult`.
    """
    @typing.final
    class Complex32(Register):
        __match_args__ = ("_0",)
        @property
        def _0(self) -> builtins.list[builtins.complex]: ...
        def __getitem__(self, key: builtins.int) -> typing.Any: ...
        def __len__(self) -> builtins.int: ...
        def __new__(cls, _0: typing.Sequence[builtins.complex]) -> Register.Complex32: ...
    
    @typing.final
    class I32(Register):
        __match_args__ = ("_0",)
        @property
        def _0(self) -> builtins.list[builtins.int]: ...
        def __getitem__(self, key: builtins.int) -> typing.Any: ...
        def __len__(self) -> builtins.int: ...
        def __new__(cls, _0: typing.Sequence[builtins.int]) -> Register.I32: ...
    
    ...

class SubmissionError(QpuApiError):
    r"""
    Errors that may occur when submitting a program for execution.
    """
    ...

def cancel_job(job_id: builtins.str, quantum_processor_id: typing.Optional[builtins.str] = None, client: typing.Optional[QCSClient] = None, execution_options: typing.Optional[ExecutionOptions] = None) -> None: ...

def cancel_job_async(job_id: builtins.str, quantum_processor_id: typing.Optional[builtins.str] = None, client: typing.Optional[QCSClient] = None, execution_options: typing.Optional[ExecutionOptions] = None) -> collections.abc.Awaitable[None]: ...

def cancel_jobs(job_ids: typing.Sequence[builtins.str], quantum_processor_id: typing.Optional[builtins.str] = None, client: typing.Optional[QCSClient] = None, execution_options: typing.Optional[ExecutionOptions] = None) -> None: ...

def cancel_jobs_async(job_ids: typing.Sequence[builtins.str], quantum_processor_id: typing.Optional[builtins.str] = None, client: typing.Optional[QCSClient] = None, execution_options: typing.Optional[ExecutionOptions] = None) -> collections.abc.Awaitable[None]: ...

def retrieve_results(job_id: builtins.str, quantum_processor_id: typing.Optional[builtins.str] = None, client: typing.Optional[QCSClient] = None, execution_options: typing.Optional[ExecutionOptions] = None) -> ExecutionResults: ...

def retrieve_results_async(job_id: builtins.str, quantum_processor_id: typing.Optional[builtins.str] = None, client: typing.Optional[QCSClient] = None, execution_options: typing.Optional[ExecutionOptions] = None) -> collections.abc.Awaitable[ExecutionResults]: ...

def submit(program: builtins.str, patch_values: typing.Mapping[builtins.str, typing.Sequence[builtins.float]], quantum_processor_id: typing.Optional[builtins.str] = None, client: typing.Optional[QCSClient] = None, execution_options: typing.Optional[ExecutionOptions] = None) -> builtins.str:
    r"""
    Submits an executable `program` to be run on the specified QPU
    
    # Errors
    
    May return an error if
    * an engagement is not available
    * an RPCQ client cannot be built
    * the program cannot be submitted
    """

def submit_async(program: builtins.str, patch_values: typing.Mapping[builtins.str, typing.Sequence[builtins.float]], quantum_processor_id: typing.Optional[builtins.str] = None, client: typing.Optional[QCSClient] = None, execution_options: typing.Optional[ExecutionOptions] = None) -> collections.abc.Awaitable[builtins.str]:
    r"""
    Submits an executable `program` to be run on the specified QPU
    
    # Errors
    
    May return an error if
    * an engagement is not available
    * an RPCQ client cannot be built
    * the program cannot be submitted
    """

def submit_with_parameter_batch(program: builtins.str, patch_values: typing.Sequence[typing.Mapping[builtins.str, typing.Sequence[builtins.float]]], quantum_processor_id: typing.Optional[builtins.str] = None, client: typing.Optional[QCSClient] = None, execution_options: typing.Optional[ExecutionOptions] = None) -> builtins.list[builtins.str]: ...

def submit_with_parameter_batch_async(program: builtins.str, patch_values: typing.Sequence[typing.Mapping[builtins.str, typing.Sequence[builtins.float]]], quantum_processor_id: typing.Optional[builtins.str] = None, client: typing.Optional[QCSClient] = None, execution_options: typing.Optional[ExecutionOptions] = None) -> collections.abc.Awaitable[builtins.list[builtins.str]]: ...

