# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401

import builtins
import collections.abc
import typing
from qcs_sdk import QcsSdkError
from qcs_sdk.client import QCSClient

@typing.final
class Architecture:
    r"""
    Represents the logical underlying architecture of a quantum processor.
    
    The architecture is defined in detail by the nodes and edges that constitute the quantum
    processor. This defines the set of all nodes that could be operated upon, and indicates to
    some approximation their physical layout. The main purpose of this is to support geometry
    calculations that are independent of the available operations, and rendering ISA-based
    information. Architecture layouts are defined by the `family`, as follows.
    
    The "Aspen" family of quantum processor indicates a 2D planar grid layout of octagon unit
    cells. The `node_id` in this architecture is computed as :math:`100 p_y + 10 p_x + p_u` where
    :math:`p_y` is the zero-based Y position in the unit cell grid, :math:`p_x` is the zero-based
    X position in the unit cell grid, and :math:`p_u` is the zero-based position in the octagon
    unit cell and always ranges from 0 to 7.
    
    The "Ankaa" architecture is based on a grid topology; having, in "vertical" orientation,
    qubits numbered starting from 0 at the top-left and increasing from left to right,
    then top to bottom, so the final qubit is in the bottom-right. Each qubit is connected
    with a tunable coupler to their direct vertical and horizontal neighbors, producing an edge.
    Edges are ordered top-left to bottom-right in this orientation as well, with horizontal rows
    alternating with vertical rows. Ankaa chips are, in vertical orientation,
    7 qubits wide and 12 tall. This architecture may also be presented in "landscape"
    orientation, which is a simple 90-degree clockwise rotation of the vertical orientation.
    
    Note that the operations that are actually available are defined entirely by ``Operation``
    instances. The presence of a node or edge in the ``Architecture`` model provides no guarantee
    that any 1Q or 2Q operation will be available to users writing QUIL programs.
    """
    @property
    def edges(self) -> builtins.list[Edge]:
        r"""
        A list of all computational edges in the instruction set architecture.
        """
    @property
    def family(self) -> typing.Optional[Family]:
        r"""
        The architecture family. The nodes and edges conform to this family.
        """
    @property
    def nodes(self) -> builtins.list[Node]:
        r"""
        A list of all computational nodes in the instruction set architecture.
        """

@typing.final
class Characteristic:
    r"""
    A measured characteristic of an operation.
    """
    @property
    def error(self) -> typing.Optional[builtins.float]:
        r"""
        The error in the characteristic value, or None if otherwise.
        """
    @property
    def name(self) -> builtins.str:
        r"""
        The name of the characteristic.
        """
    @property
    def node_ids(self) -> typing.Optional[builtins.list[builtins.int]]:
        r"""
        The list of architecture node ids for the site where the characteristic is
        measured, if that is different from the site of the enclosing operation.
        `None` if it is the same. The order of this or the enclosing node ids obey
        the definition of node symmetry from the enclosing operation.
        """
    @property
    def parameter_values(self) -> typing.Optional[builtins.list[builtins.float]]:
        r"""
        The optional ordered list of parameter values used to generate the characteristic.
        The order matches the parameters in the enclosing operation, and so the lengths of
        these two lists must match.
        """
    @property
    def timestamp(self) -> builtins.str:
        r"""
        ISO8601 date and time at which the characteristic was measured.
        """
    @property
    def value(self) -> builtins.float:
        r"""
        The characteristic value measured.
        """

@typing.final
class Edge:
    r"""
    A degree-two logical connection in the quantum processor's architecture.
    
    The existence of an edge in the ISA ``Architecture`` does not necessarily mean that a given 2Q
    operation will be available on the edge. This information is conveyed by the presence of the
    two `node_id` values in instances of ``Instruction``.
    
    Note that edges are undirected in this model. Thus edge :math:`(a, b)` is equivalent to edge
    :math:`(b, a)`.
    """
    @property
    def node_ids(self) -> builtins.list[builtins.int]:
        r"""
        The integer ids of the computational nodes at the two ends of the edge.
        Order is not important; an architecture edge is treated as undirected.
        """

@typing.final
class Family:
    r"""
    The architecture family identifier of an ``InstructionSetArchitecture``.
    
    Value "Full" implies that each node is connected to every other (fully-connected architecture).
    """
    ...

class GetISAError(QcsSdkError):
    r"""
    Errors raised due to failure to get an ISA.
    """
    ...

@typing.final
class InstructionSetArchitecture:
    r"""
    The native instruction set architecture (ISA) of a quantum processor, annotated with characteristics.
    
    The operations described by the `instructions` field are named by their QUIL instruction name,
    while the operation described by the `benchmarks` field are named by their benchmark routine
    and are a future extension point.
    
    The characteristics that annotate both instructions and benchmarks assist the user to generate
    the best native QUIL program for a desired task, and so are provided as part of the native ISA.
    """
    @property
    def architecture(self) -> Architecture:
        r"""
        The architecture of the quantum processor.
        """
    @architecture.setter
    def architecture(self, value: Architecture) -> None: ...
    @property
    def benchmarks(self) -> builtins.list[Operation]:
        r"""
        The list of benchmarks that have characterized the quantum processor.
        """
    @benchmarks.setter
    def benchmarks(self, value: builtins.list[Operation]) -> None: ...
    @property
    def instructions(self) -> builtins.list[Operation]:
        r"""
        The list of native QUIL instructions supported by the quantum processor.
        """
    @instructions.setter
    def instructions(self, value: builtins.list[Operation]) -> None: ...
    @property
    def name(self) -> builtins.str:
        r"""
        The name of the quantum processor.
        """
    @name.setter
    def name(self, value: builtins.str) -> None: ...
    @staticmethod
    def from_raw(json: builtins.str) -> InstructionSetArchitecture:
        r"""
        Deserialize an [`InstructionSetArchitecture`] from a json representation.
        
        # Errors
        
        Returns `[SerializeIsaError`] if the input string was not deserialized correctly.
        """
    def json(self, pretty: builtins.bool = False) -> builtins.str:
        r"""
        Serialize the ``InstructionSetArchitecture`` to a json string, optionally pretty-printed.
        
        If `pretty` is true, the json output should be pretty-printed with newlines and indents.
        
        # Errors
        
        Returns [`SerializeIsaError`] if the ISA could not be serialized.
        """

@typing.final
class Node:
    r"""
    A logical node in the quantum processor's architecture.
    
    The existence of a node in the ISA ``Architecture`` does not necessarily mean that a given 1Q
    operation will be available on the node. This information is conveyed by the presence of the
    specific `node_id` in instances of ``Instruction``.
    """
    @property
    def node_id(self) -> builtins.int:
        r"""
        An integer id assigned to the computational node.
        The ids may not be contiguous and will be assigned based on the architecture family.
        """

@typing.final
class Operation:
    r"""
    An operation, with its sites and site-independent characteristics.
    """
    @property
    def characteristics(self) -> builtins.list[Characteristic]:
        r"""
        The list of site-independent characteristics of this operation.
        """
    @property
    def name(self) -> builtins.str:
        r"""
        The name of the operation.
        """
    @property
    def node_count(self) -> typing.Optional[builtins.int]:
        r"""
        The number of nodes that this operation applies to. None if unspecified.
        """
    @property
    def parameters(self) -> builtins.list[Parameter]:
        r"""
        The list of parameters. Each parameter must be uniquely named. May be empty.
        """
    @property
    def sites(self) -> builtins.list[OperationSite]:
        r"""
        The list of sites at which this operation can be applied,
        together with its site-dependent characteristics.
        """

@typing.final
class OperationSite:
    r"""
    A site for an operation, with its site-dependent characteristics.
    """
    @property
    def characteristics(self) -> builtins.list[Characteristic]:
        r"""
        The list of site-dependent characteristics of this operation.
        """
    @property
    def node_ids(self) -> builtins.list[builtins.int]:
        r"""
        The list of architecture node ids for the site. The order of these node ids
        obey the definition of node symmetry from the enclosing operation.
        """

@typing.final
class Parameter:
    r"""
    A parameter to an operation.
    """
    @property
    def name(self) -> builtins.str:
        r"""
        The name of the parameter, such as the name of a mathematical symbol.
        """

class SerializeISAError(QcsSdkError):
    r"""
    Errors raised due to failure to serialize an ISA.
    """
    ...

def get_instruction_set_architecture(quantum_processor_id: builtins.str, client: typing.Optional[QCSClient] = None) -> InstructionSetArchitecture:
    r"""
    Fetch the ``InstructionSetArchitecture`` (ISA) for a given `quantum_processor_id` from the QCS API.
    
    :param quantum_processor_id: The ID of the quantum processor.
    :param client: The ``Qcs`` client to use. Creates one using environment configuration if unset - see https://docs.rigetti.com/qcs/references/qcs-client-configuration
    
    :raises LoadClientError: If ``client`` was not provided to the function, and failed to load internally.
    :raises GetISAError: If there was an issue fetching the ISA from the QCS API.
    """

def get_instruction_set_architecture_async(quantum_processor_id: builtins.str, client: typing.Optional[QCSClient] = None) -> collections.abc.Awaitable[InstructionSetArchitecture]:
    r"""
    Fetch the ``InstructionSetArchitecture`` (ISA) for a given `quantum_processor_id` from the QCS API.
    
    :param quantum_processor_id: The ID of the quantum processor.
    :param client: The ``Qcs`` client to use. Creates one using environment configuration if unset - see https://docs.rigetti.com/qcs/references/qcs-client-configuration
    
    :raises LoadClientError: If ``client`` was not provided to the function, and failed to load internally.
    :raises GetISAError: If there was an issue fetching the ISA from the QCS API.
    """

