# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401

import builtins
import typing
from qcs_sdk import QcsSdkError
from qcs_sdk.client import QCSClient

class Architecture:
    ...

class Characteristic:
    ...

class Edge:
    ...

class Family:
    ...

class GetISAError(QcsSdkError):
    r"""
    Errors raised due to failure to get an ISA.
    """
    ...

class InstructionSetArchitecture:
    @staticmethod
    def from_raw(json:builtins.str) -> InstructionSetArchitecture: ...
    def json(self, pretty:builtins.bool=False) -> builtins.str: ...

class Node:
    ...

class Operation:
    ...

class OperationSite:
    ...

class Parameter:
    ...

class SerializeISAError(QcsSdkError):
    r"""
    Errors raised due to failure to serialize an ISA.
    """
    ...

def get_instruction_set_architecture(quantum_processor_id:builtins.str, client:typing.Optional[QCSClient]=None) -> InstructionSetArchitecture: ...

def get_instruction_set_architecture_async(quantum_processor_id:builtins.str, client:typing.Optional[QCSClient]=None) -> typing.Any: ...

