# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401

import builtins
import collections.abc
import typing
from qcs_sdk import QcsSdkError
from qcs_sdk.client import QCSClient

@typing.final
class Architecture:
    @property
    def edges(self) -> builtins.list[Edge]: ...
    @property
    def family(self) -> typing.Optional[Family]: ...
    @property
    def nodes(self) -> builtins.list[Node]: ...

@typing.final
class Characteristic:
    @property
    def error(self) -> typing.Optional[builtins.float]: ...
    @property
    def name(self) -> builtins.str: ...
    @property
    def node_ids(self) -> typing.Optional[builtins.list[builtins.int]]: ...
    @property
    def parameter_values(self) -> typing.Optional[builtins.list[builtins.float]]: ...
    @property
    def timestamp(self) -> builtins.str: ...
    @property
    def value(self) -> builtins.float: ...

@typing.final
class Edge:
    @property
    def node_ids(self) -> builtins.list[builtins.int]: ...

@typing.final
class Family:
    ...

class GetISAError(QcsSdkError):
    r"""
    Errors raised due to failure to get an ISA.
    """
    ...

@typing.final
class InstructionSetArchitecture:
    @property
    def architecture(self) -> Architecture: ...
    @property
    def benchmarks(self) -> builtins.list[Operation]: ...
    @benchmarks.setter
    def benchmarks(self, value: builtins.list[Operation]) -> None: ...
    @property
    def instructions(self) -> builtins.list[Operation]: ...
    @property
    def name(self) -> builtins.str: ...
    @staticmethod
    def from_raw(json: builtins.str) -> InstructionSetArchitecture: ...
    def json(self, pretty: builtins.bool = False) -> builtins.str: ...

@typing.final
class Node:
    @property
    def node_id(self) -> builtins.int: ...

@typing.final
class Operation:
    @property
    def characteristics(self) -> builtins.list[Characteristic]: ...
    @property
    def name(self) -> builtins.str: ...
    @property
    def node_count(self) -> typing.Optional[builtins.int]: ...
    @property
    def parameters(self) -> builtins.list[Parameter]: ...
    @property
    def sites(self) -> builtins.list[OperationSite]: ...

@typing.final
class OperationSite:
    @property
    def characteristics(self) -> builtins.list[Characteristic]: ...
    @property
    def node_ids(self) -> builtins.list[builtins.int]: ...

@typing.final
class Parameter:
    @property
    def name(self) -> builtins.str: ...

class SerializeISAError(QcsSdkError):
    r"""
    Errors raised due to failure to serialize an ISA.
    """
    ...

def get_instruction_set_architecture(quantum_processor_id: builtins.str, client: typing.Optional[QCSClient] = None) -> InstructionSetArchitecture: ...

def get_instruction_set_architecture_async(quantum_processor_id: builtins.str, client: typing.Optional[QCSClient] = None) -> collections.abc.Awaitable[InstructionSetArchitecture]: ...

