# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401

import builtins
import typing
from qcs_sdk import QcsSdkError
from qcs_sdk.client import QCSClient
from enum import Enum

class QCtrl:
    def __new__(cls, fixed_layout:typing.Optional[builtins.bool]=None) -> QCtrl: ...

class Riverlane:
    def __new__(cls, qeci_configuration_data:typing.Mapping[builtins.str, typing.Sequence[builtins.int]], qeci_max_nanoseconds_until_read_available:builtins.int) -> Riverlane: ...

class TranslationError(QcsSdkError):
    r"""
    Errors raised due to failure to translate a program.
    """
    ...

class TranslationOptions:
    ...

class TranslationOptions:
    r"""
    Options available for Quil program translation.
    
    This wraps [`ApiTranslationOptions`] in order to improve the user experience,
    because the structs auto-generated by `prost` can be clumsy to use directly.
    """
    def __repr__(self) -> builtins.str: ...
    def backend(self) -> typing.Optional[TranslationBackend]:
        r"""
        Get the backend used for translation
        """
    def encode_as_protobuf(self) -> bytes: ...
    def use_backend_v1(self) -> None: ...
    def use_backend_v2(self) -> None: ...
    def use_q_ctrl(self, q_ctrl:QCtrl=...) -> None: ...
    def use_riverlane(self, riverlane:Riverlane=...) -> None: ...
    @staticmethod
    def v1() -> TranslationOptions: ...
    @staticmethod
    def v2(*, prepend_default_calibrations:typing.Optional[builtins.bool]=None, passive_reset_delay_seconds:typing.Optional[builtins.float]=None, allow_unchecked_pointer_arithmetic:typing.Optional[builtins.bool]=None, allow_frame_redefinition:typing.Optional[builtins.bool]=None) -> TranslationOptions: ...

class TranslationResult:
    r"""
    The result of a call to [`translate`] which provides information about the
    translated program.
    """
    @property
    def program(self) -> builtins.str:
        r"""
        The translated program.
        """
    @property
    def ro_sources(self) -> typing.Optional[builtins.dict[builtins.str, builtins.str]]:
        r"""
        The memory locations used for readout.
        """

class TranslationBackend(Enum):
    V1 = ...
    V2 = ...

def get_quilt_calibrations(quantum_processor_id:builtins.str, client:typing.Optional[QCSClient]=None, timeout:typing.Optional[builtins.float]=None) -> builtins.str:
    r"""
    Query the QCS API for Quil-T calibrations.
    If `None`, the default `timeout` used is 10 seconds.
    """

def get_quilt_calibrations_async(quantum_processor_id:builtins.str, client:typing.Optional[QCSClient]=None, timeout:typing.Optional[builtins.float]=None) -> typing.Any:
    r"""
    Query the QCS API for Quil-T calibrations.
    If `None`, the default `timeout` used is 10 seconds.
    """

def translate(native_quil:builtins.str, num_shots:builtins.int, quantum_processor_id:builtins.str, client:typing.Optional[QCSClient]=None, translation_options:typing.Optional[TranslationOptions]=None) -> TranslationResult:
    r"""
    Translates a native Quil program into an executable
    
    # Errors
    
    Returns a [`TranslationError`] if translation fails.
    """

def translate_async(native_quil:builtins.str, num_shots:builtins.int, quantum_processor_id:builtins.str, client:typing.Optional[QCSClient]=None, translation_options:typing.Optional[TranslationOptions]=None) -> typing.Any:
    r"""
    Translates a native Quil program into an executable
    
    # Errors
    
    Returns a [`TranslationError`] if translation fails.
    """

